config/routes.rb
Tangentz::Application.routes.draw do
  devise_for :users
  resources :tangents

end

app/models/tangent.rb
class Tangent < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tangents_controller.rb
class TangentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tangent, only: [:show, :edit, :update, :destroy]

  # GET /tangents
  # GET /tangents.json
  def index
    @tangents = Tangent.all
  end

  # GET /tangents/1
  # GET /tangents/1.json
  def show
  end

  # GET /tangents/new
  def new
    @tangent = Tangent.new
  end

  # GET /tangents/1/edit
  def edit
  end

  # POST /tangents
  # POST /tangents.json
  def create
    @tangent = Tangent.new(tangent_params)

    respond_to do |format|
      if @tangent.save
        format.html { redirect_to @tangent, notice: 'Tangent was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tangent }
      else
        format.html { render action: 'new' }
        format.json { render json: @tangent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tangents/1
  # PATCH/PUT /tangents/1.json
  def update
    respond_to do |format|
      if @tangent.update(tangent_params)
        format.html { redirect_to @tangent, notice: 'Tangent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tangent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tangents/1
  # DELETE /tangents/1.json
  def destroy
    @tangent.destroy
    respond_to do |format|
      format.html { redirect_to tangents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tangent
      @tangent = Tangent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tangent_params
      params.require(:tangent).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tangents_helper.rb
module TangentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tangentz</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tangents/_form.html.erb
<%= form_for(@tangent) do |f| %>
  <% if @tangent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tangent.errors.count, "error") %> prohibited this tangent from being saved:</h2>

      <ul>
      <% @tangent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tangents/edit.html.erb
<h1>Editing tangent</h1>

<%= render 'form' %>

<%= link_to 'Show', @tangent %> |
<%= link_to 'Back', tangents_path %>

app/views/tangents/index.html.erb
<h1>Listing tangents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tangents.each do |tangent| %>
      <tr>
        <td><%= tangent.name %></td>
        <td><%= tangent.description %></td>
        <td><%= link_to 'Show', tangent %></td>
        <td><%= link_to 'Edit', edit_tangent_path(tangent) %></td>
        <td><%= link_to 'Destroy', tangent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tangent', new_tangent_path %>

app/views/tangents/new.html.erb
<h1>New tangent</h1>

<%= render 'form' %>

<%= link_to 'Back', tangents_path %>

app/views/tangents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tangent.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tangent.description %>
</p>

<%= link_to 'Edit', edit_tangent_path(@tangent) %> |
<%= link_to 'Back', tangents_path %>